# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
  Azure.ServiceConnectionId: 'nebbia-partner-network'
  ACR.ContainerRegistryServiceConnnection: 'nebbia-container-registry'
  AKS.ServiceConnectionId: 'nebbia-partner-network'
  ACR.Name: nebbiaregistry
  Chart.Name: codecampster
  Service.Name: mvc
  Image.Name: codecampster/mvc
  Service.Dockerfile: src/Codecamp/Dockerfile
  Release.Name: codecampster
  # ========================================================================
  #                           Optional variables 
  # ========================================================================
  ACR.RepositoryName: '$(ACR.Name)'
  ACR.ImageName: '$(ACR.Name):$(Build.BuildId)'
  ACR.FullName: '$(ACR.Name).azurecr.io'
  ACR.ImageFullName: '$(ACR.FullName)/$(Image.Name)'
  System.Debug: 'false'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: $(ACR.ContainerRegistryServiceConnnection)
        repository: codecampster/$(Service.Name)
        buildContext: .
        Dockerfile: $(Service.Dockerfile)
        tags: $(Build.BuildNumber)